/**
 * ONNX 模块消息动作配置
 */
export const ONNX_ACTIONS = {
  /** 模块名称 */
  MODULE_NAME: 'ONNX',
  SHARED_NAME: 'SHARED_ONNX',

  /** 动作类型 */
  INIT: 'INIT',
  LOAD_MODEL: 'LOAD_MODEL',
  RUN_INFERENCE: 'RUN_INFERENCE',
  INFERENCE_RUNNING: 'INFERENCE_RUNNING',
  INFERENCE_COMPLETED: 'INFERENCE_COMPLETED',
  GET_STATUS: 'GET_STATUS',
};
