/**
 * WebRTC 模块消息动作配置
 */
export const WEBRTC_ACTIONS = {
  /** 模块名称 */
  MODULE_NAME: 'WEBRTC',
  SHARED_NAME: 'SHARED_WEBRTC',

  /** 动作类型 */
  INIT: 'INIT',
  READY: 'READY',
  ERROR: 'ERROR',
  GET_PEER_ID: 'GET_PEER_ID',
  SEND_DATA: 'SEND_DATA',
  DISCONNECT: 'DISCONNECT',
  GET_STATUS: 'GET_STATUS',

  /** 连接事件 */
  CONNECTION_OPENED: 'CONNECTION_OPENED',
  CONNECTION_CLOSED: 'CONNECTION_CLOSED',
  CONNECTION_ERROR: 'CONNECTION_ERROR',

  /** Peer 状态事件 */
  DISCONNECTED: 'DISCONNECTED',
  CLOSED: 'CLOSED',
};
